name: Send email new RSS Feed items	
on:
  rss:
    url: https://hnrss.org/newest?points=300&count=1
jobs:
  email:
    name: Post a email
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.zoho.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ${{ on.rss.outputs.title }}
          # Literal body:
          body: ${{ on.rss.outputs.content }}
          # Read file contents as body:
          to: theowenyoung@gmail.com
          from: theowenyoung@zohomail.com # <user@example.com>
          # Optional content type (defaults to text/plain):
          content_type: text/html